language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
branches:
  only:
  - master
before_deploy: "cd functions && npm install && cd -"
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: lwDg1GB6IFs3S9vWd1tqyfJtMzWian5anrPL+gRvPPgdw5WakEcNQ2kQBrYmOirZdRp7jxqK2Y92cLEvx7iO6A0XZ62B61bZ2EzDkflKTjtcSykm7bIHdWOSGRwGVl9yQfwTs5YYB91SfZK1OHGxj1IPtppdr9YXhNq1ae/a1SFwtR5dE+FXG1eVrot7uynKxDKiyealccqKNGQS1J5UIZuiJ+uemiK1jXwWS4vVO9Z5mVMJWG7EDpx1jl2nKNhwp43kzEVpZnUPLzFBioeFAzP+ZXFuEsOv1oApsVYuUyJBfi2MGfVWFDBeJ0I2nS/m665xCKJwRq9G7zU+Zpp1a0HEcZlgECZW3QevHlNArxq6ryjYlFyvWYg5y6AqRj2QlyBdIE3FLobPftKXhaSB/NHTA8jkfQMqEaJNJzSQNDGjuTESWcJgWx0l02u4jE57wthqlPHMjhLMxDuUF+z+ipLPK/umTnbvAANpsrV33cqC/WFfTlUpnfJnLdTnJ6GIaY592YFfcz9BLHW1j2pHHjfuTM8ZGeCzVBb+DJlwHZbT7EkiPhJEXo5kze/iDkrkdoHfhXnl/+2uhhIcPex4xipJu5Tk6Mj5You6r4wgBhC7VRGs2mqrM8fgmkv5TL0avjH65T0Q4EeYf6clrDqxpdaDOgm3GdqWs7ocRzodwF8=
env:
  global:
    secure: lwDg1GB6IFs3S9vWd1tqyfJtMzWian5anrPL+gRvPPgdw5WakEcNQ2kQBrYmOirZdRp7jxqK2Y92cLEvx7iO6A0XZ62B61bZ2EzDkflKTjtcSykm7bIHdWOSGRwGVl9yQfwTs5YYB91SfZK1OHGxj1IPtppdr9YXhNq1ae/a1SFwtR5dE+FXG1eVrot7uynKxDKiyealccqKNGQS1J5UIZuiJ+uemiK1jXwWS4vVO9Z5mVMJWG7EDpx1jl2nKNhwp43kzEVpZnUPLzFBioeFAzP+ZXFuEsOv1oApsVYuUyJBfi2MGfVWFDBeJ0I2nS/m665xCKJwRq9G7zU+Zpp1a0HEcZlgECZW3QevHlNArxq6ryjYlFyvWYg5y6AqRj2QlyBdIE3FLobPftKXhaSB/NHTA8jkfQMqEaJNJzSQNDGjuTESWcJgWx0l02u4jE57wthqlPHMjhLMxDuUF+z+ipLPK/umTnbvAANpsrV33cqC/WFfTlUpnfJnLdTnJ6GIaY592YFfcz9BLHW1j2pHHjfuTM8ZGeCzVBb+DJlwHZbT7EkiPhJEXo5kze/iDkrkdoHfhXnl/+2uhhIcPex4xipJu5Tk6Mj5You6r4wgBhC7VRGs2mqrM8fgmkv5TL0avjH65T0Q4EeYf6clrDqxpdaDOgm3GdqWs7ocRzodwF8=
